// <auto-generated />
using System;
using AspTechTrader.Infrastructure.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspTechTrader.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240831125542_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspTechTrader.Core.Domain.Entities.Symbol", b =>
                {
                    b.Property<Guid>("SymbolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SymbolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("chartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("demandPrice")
                        .HasColumnType("int");

                    b.Property<int?>("demandVolume")
                        .HasColumnType("int");

                    b.Property<int?>("lastDeal")
                        .HasColumnType("int");

                    b.Property<float?>("lastDealPercentage")
                        .HasColumnType("real");

                    b.Property<int?>("lastPrice")
                        .HasColumnType("int");

                    b.Property<float?>("lastPricePercentage")
                        .HasColumnType("real");

                    b.Property<int?>("offerPrice")
                        .HasColumnType("int");

                    b.Property<int?>("offerVolume")
                        .HasColumnType("int");

                    b.Property<int?>("state")
                        .HasColumnType("int");

                    b.Property<int?>("theFirst")
                        .HasColumnType("int");

                    b.Property<int?>("theLeast")
                        .HasColumnType("int");

                    b.Property<int?>("theMost")
                        .HasColumnType("int");

                    b.Property<int?>("volume")
                        .HasColumnType("int");

                    b.HasKey("SymbolId");

                    b.ToTable("Symbols");
                });
#pragma warning restore 612, 618
        }
    }
}
